/**
 * @description: Description
 * @author: lizlong<94648929@qq.com>
 * @since: 2019-11-08 12:53:26
 * @LastAuthor: lizlong
 * @lastTime: 2021-03-04 10:15:16
 */
let components = [{
  id: 1,
  label: "边框",
  icon: "el-icon-takeaway-box",
  children: [{
    id: 1001,
    label: "边框一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-1",
  }, {
    id: 1002,
    label: "边框二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-2",
  }, {
    id: 1003,
    label: "边框三",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-3",
  }, {
    id: 1004,
    label: "边框四",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-4",
  }, {
    id: 1005,
    label: "边框五",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-5",
  }, {
    id: 1006,
    label: "边框六",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-6",
  }, {
    id: 1007,
    label: "边框七",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-7",
  }, {
    id: 1008,
    label: "边框八",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-8",
  }, {
    id: 1009,
    label: "边框九",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-9",
  }, {
    id: 1010,
    label: "边框十",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-10",
  }, {
    id: 1011,
    label: "边框十一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-11",
  }, {
    id: 1012,
    label: "边框十二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-12",
  }, {
    id: 1013,
    label: "边框十三",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-13",
  }]
}, {
  id: 2,
  label: "装饰",
  icon: "el-icon-brush",
  children: [{
    id: 2001,
    label: "装饰一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-1",
  }, {
    id: 2002,
    label: "装饰二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-2",
  }, {
    id: 2003,
    label: "装饰三",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-3",
  }, {
    id: 2004,
    label: "装饰四",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-4",
  }, {
    id: 2005,
    label: "装饰五",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-5",
  }, {
    id: 2006,
    label: "装饰六",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-6",
  }, {
    id: 2007,
    label: "装饰七",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-7",
  }, {
    id: 2008,
    label: "装饰八",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-8",
  }, {
    id: 2009,
    label: "装饰九",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-9",
  }, {
    id: 2010,
    label: "装饰十",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-10",
  }, {
    id: 2011,
    label: "装饰十一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-11",
  }, {
    id: 2012,
    label: "装饰十二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-12",
  }]
}, {
  id: 3,
  label: "图表",
  icon: "el-icon-data-line",
  children: [
    {
      id: 3001,
      label: "动态环图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-active-ring-chart",
    }, {
      id: 3002,
      label: "胶囊柱图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-capsule-chart",
    }, {
      id: 3003,
      label: "水位图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-water-level-pond",
    }, {
      id: 3004,
      label: "进度池",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-percent-pond",
    }, {
      id: 3005,
      label: "飞线图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-flyline-chart",
    }, {
      id: 3006,
      label: "飞线图增强版",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-flyline-chart-enhanced",
    }, {
      id: 3007,
      label: "锥形柱图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-conical-column-chart",
    }, {
      id: 3008,
      label: "数字翻牌器",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-digital-flop",
    }, {
      id: 3009,
      label: "轮播表",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-scroll-board",
    }, {
      id: 3010,
      label: "排名轮播表",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-scroll-ranking-board",
    }
  ]
}]

export {
  components
};