/**
 * @description: Description
 * @author: lizlong<94648929@qq.com>
 * @since: 2019-11-08 12:53:26
 * @LastAuthor: lizlong
 * @lastTime: 2021-03-03 16:37:29
 */
let components = [{
  id: 1,
  label: "边框",
  icon: "el-icon-takeaway-box",
  children: [{
    id: 101,
    label: "边框一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-1",
  }, {
    id: 102,
    label: "边框二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-2",
  }, {
    id: 102,
    label: "边框三",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-3",
  }, {
    id: 102,
    label: "边框四",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-4",
  }, {
    id: 102,
    label: "边框五",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-5",
  }, {
    id: 102,
    label: "边框六",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-6",
  }, {
    id: 102,
    label: "边框七",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-7",
  }, {
    id: 102,
    label: "边框八",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-8",
  }, {
    id: 102,
    label: "边框九",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-9",
  }, {
    id: 102,
    label: "边框十",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-10",
  }, {
    id: 102,
    label: "边框十一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-11",
  }, {
    id: 102,
    label: "边框十二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-12",
  }, {
    id: 102,
    label: "边框十三",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-border-Box-13",
  }]
}, {
  id: 2,
  label: "装饰",
  icon: "el-icon-brush",
  children: [{
    id: 201,
    label: "装饰一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-1",
  }, {
    id: 202,
    label: "装饰二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-2",
  }, {
    id: 202,
    label: "装饰三",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-3",
  }, {
    id: 202,
    label: "装饰四",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-4",
  }, {
    id: 202,
    label: "装饰五",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-5",
  }, {
    id: 202,
    label: "装饰六",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-6",
  }, {
    id: 202,
    label: "装饰七",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-7",
  }, {
    id: 202,
    label: "装饰八",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-8",
  }, {
    id: 202,
    label: "装饰九",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-9",
  }, {
    id: 202,
    label: "装饰十",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-10",
  }, {
    id: 202,
    label: "装饰十一",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-11",
  }, {
    id: 202,
    label: "装饰十二",
    span: 24,
    icon: "el-icon-data-line",
    component: "dv-decoration-12",
  }]
}, {
  id: 3,
  label: "图表",
  icon: "el-icon-data-line",
  children: [
    {
      id: 202,
      label: "动态环图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-active-ring-chart",
    }, {
      id: 202,
      label: "胶囊柱图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-capsule-chart",
    }, {
      id: 202,
      label: "水位图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-water-level-pond",
    }, {
      id: 202,
      label: "进度池",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-percent-pond",
    }, {
      id: 202,
      label: "飞线图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-flyline-chart",
    }, {
      id: 202,
      label: "飞线图增强版",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-flyline-chart-enhanced",
    }, {
      id: 202,
      label: "锥形柱图",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-conical-column-chart",
    }, {
      id: 202,
      label: "数字翻牌器",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-digital-flop",
    }, {
      id: 202,
      label: "轮播表",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-scroll-board",
    }, {
      id: 202,
      label: "排名轮播表",
      span: 24,
      icon: "el-icon-data-line",
      component: "dv-scroll-ranking-board",
    }
  ]
}]

export {
  components
};